import { ScheduleEvent, UniversityCourse, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: 'Rina',
  university: 'Pacific Coast University',
  major: 'Computer Science & Visual Design',
  semester: 'Fall Semester 2026',
  semesterStart: '2026-09-01',
  semesterEnd: '2026-12-20',
};

export const INITIAL_COURSES: UniversityCourse[] = [
  {
    id: 'course-1',
    code: 'CS302',
    name: 'Database Systems',
    instructor: 'Prof. David Vance',
    room: 'Building 24 — Room 302',
    days: ['Monday', 'Wednesday'],
    startTime: '08:00',
    endTime: '09:30',
    color: '#84A98C', // Sage green
    credits: 4,
    semester: 'Fall 2026',
  },
  {
    id: 'course-2',
    code: 'CS210',
    name: 'Data Structures & Java',
    instructor: 'Prof. Helen Lin',
    room: 'Building 12 — Room 105',
    days: ['Sunday', 'Tuesday'],
    startTime: '10:00',
    endTime: '11:30',
    color: '#E07A5F', // Terracotta
    credits: 4,
    semester: 'Fall 2026',
  },
  {
    id: 'course-3',
    code: 'ART150',
    name: 'Visual Design & Color Theory',
    instructor: 'Prof. Sofia Morales',
    room: 'Fine Arts Pavilion — Studio B',
    days: ['Thursday'],
    startTime: '14:00',
    endTime: '16:00',
    color: '#F4A261', // Soft orange
    credits: 3,
    semester: 'Fall 2026',
  },
  {
    id: 'course-4',
    code: 'ENG201',
    name: 'Modern Literature & Ethics',
    instructor: 'Prof. Julian Sterling',
    room: 'Hall 4 — Room 201',
    days: ['Monday', 'Wednesday'],
    startTime: '11:30',
    endTime: '13:00',
    color: '#B5838D', // Warm mauve
    credits: 3,
    semester: 'Fall 2026',
  },
];

export const INITIAL_EVENTS: ScheduleEvent[] = [
  // SATURDAY · SEPTEMBER 12 (TODAY)
  {
    id: 'ev-sat-1',
    title: 'Morning Matcha & Weekly Reflection',
    category: 'personal',
    date: '2026-09-12',
    startTime: '08:30',
    endTime: '09:15',
    location: 'Dorm Balcony',
    notes: 'Brew ceremonial matcha, set mindful goals for mid-September.',
    priority: 'low',
    moodSticker: 'coffee',
  },
  {
    id: 'ev-sat-2',
    title: 'Farmers Market & Pastry Crawl',
    category: 'social',
    date: '2026-09-12',
    startTime: '10:30',
    endTime: '12:30',
    location: 'Old Town Square',
    notes: 'Meet Maya and Elena at the honey lavender stall.',
    priority: 'medium',
    moodSticker: 'heart',
  },
  {
    id: 'ev-sat-3',
    title: 'Database Systems ERD Diagram Study',
    category: 'university',
    date: '2026-09-12',
    startTime: '14:00',
    endTime: '16:00',
    location: 'Central Library — 3rd Floor Quiet Nook',
    courseCode: 'CS302',
    notes: 'Review relational normalization and indexing for Monday submission.',
    priority: 'high',
    moodSticker: 'book',
  },
  {
    id: 'ev-sat-4',
    title: 'Golden Hour Sunset Run & Stretching',
    category: 'personal',
    date: '2026-09-12',
    startTime: '17:30',
    endTime: '18:30',
    location: 'Campus West Perimeter Trail',
    notes: 'Easy 4km tempo run, listen to indie acoustic playlist.',
    priority: 'low',
    moodSticker: 'sun',
  },
  {
    id: 'ev-sat-5',
    title: 'Indie Film Screening & Gelato',
    category: 'social',
    date: '2026-09-12',
    startTime: '20:00',
    endTime: '22:00',
    location: 'Student Union Amphitheater',
    notes: 'Outdoor projection night with campus film guild.',
    priority: 'medium',
    moodSticker: 'sparkles',
  },

  // SUNDAY · SEPTEMBER 13 (TOMORROW)
  {
    id: 'ev-sun-1',
    title: 'Data Structures & Java Lecture',
    category: 'university',
    date: '2026-09-13',
    startTime: '10:00',
    endTime: '11:30',
    location: 'Building 12 — Room 105',
    room: 'Room 105',
    instructor: 'Prof. Helen Lin',
    courseCode: 'CS210',
    notes: 'Generic collections, comparator patterns, and recursive tree traversals.',
    priority: 'high',
    isRecurring: true,
    recurringDays: ['Sunday', 'Tuesday'],
    moodSticker: 'book',
  },
  {
    id: 'ev-sun-2',
    title: 'Sunday Avocado Brunch with Roommates',
    category: 'social',
    date: '2026-09-13',
    startTime: '12:30',
    endTime: '14:00',
    location: 'Sunny Side Kitchen',
    notes: 'Sourdough toast, fresh squeezed OJ, catch up on the week.',
    priority: 'medium',
    moodSticker: 'heart',
  },
  {
    id: 'ev-sun-3',
    title: 'Finish Database Systems Assignment #2',
    category: 'assignments',
    date: '2026-09-13',
    startTime: '15:30',
    endTime: '17:30',
    location: 'Room Desk',
    courseCode: 'CS302',
    notes: 'Write SQL queries for questions 4 to 8. Run EXPLAIN ANALYZE on queries.',
    priority: 'urgent',
    isTask: true,
    completed: false,
    isDeadline: true,
    moodSticker: 'star',
  },

  // MONDAY · SEPTEMBER 14 (Exact from user prompt example!)
  {
    id: 'ev-mon-1',
    title: 'Database Systems',
    category: 'university',
    date: '2026-09-14',
    startTime: '08:00',
    endTime: '09:30',
    location: 'Building 24 — Room 302',
    room: 'Room 302',
    instructor: 'Prof. David Vance',
    courseCode: 'CS302',
    notes: 'B-Trees and relational storage engines.',
    priority: 'high',
    isRecurring: true,
    recurringDays: ['Monday', 'Wednesday'],
    moodSticker: 'sun',
  },
  {
    id: 'ev-mon-2',
    title: 'Study / Free Time',
    category: 'personal',
    date: '2026-09-14',
    startTime: '11:00',
    endTime: '12:30',
    location: 'Central Quad Elm Trees',
    notes: 'Read chapter 4 of modern literature under the shade.',
    priority: 'low',
    moodSticker: 'coffee',
  },
  {
    id: 'ev-mon-3',
    title: 'Submit Database Assignment',
    category: 'assignments',
    date: '2026-09-14',
    startTime: '13:00',
    endTime: '13:15',
    location: 'Canvas Course Portal',
    courseCode: 'CS302',
    notes: 'Upload PDF and SQL schema scripts. Double check indexing benchmarks.',
    priority: 'urgent',
    isTask: true,
    completed: false,
    isDeadline: true,
    moodSticker: 'star',
  },
  {
    id: 'ev-mon-4',
    title: 'Meeting with Sara',
    category: 'social',
    date: '2026-09-14',
    startTime: '16:00',
    endTime: '17:15',
    location: 'University Café',
    notes: 'Plan the upcoming design hackathon pitch and grab iced lattes.',
    priority: 'medium',
    moodSticker: 'heart',
  },
  {
    id: 'ev-mon-5',
    title: 'Art Club Event',
    category: 'social',
    date: '2026-09-14',
    startTime: '19:00',
    endTime: '21:00',
    location: 'Fine Arts Pavilion Studio B',
    notes: 'Watercolor study & gouache experimentation night. Supplies provided!',
    priority: 'medium',
    moodSticker: 'palette',
  },

  // TUESDAY · SEPTEMBER 15
  {
    id: 'ev-tue-1',
    title: 'Data Structures & Java Lecture',
    category: 'university',
    date: '2026-09-15',
    startTime: '10:00',
    endTime: '11:30',
    location: 'Building 12 — Room 105',
    room: 'Room 105',
    instructor: 'Prof. Helen Lin',
    courseCode: 'CS210',
    notes: 'Balanced binary search trees (AVL & Red-Black trees).',
    priority: 'high',
    isRecurring: true,
    recurringDays: ['Sunday', 'Tuesday'],
    moodSticker: 'book',
  },
  {
    id: 'ev-tue-2',
    title: 'Academic Advisor Meeting',
    category: 'appointments',
    date: '2026-09-15',
    startTime: '14:00',
    endTime: '14:45',
    location: 'Student Affairs Hall — Room 410',
    instructor: 'Dr. Katherine Bell',
    notes: 'Discuss Spring study-abroad program eligibility and major capstone tracks.',
    priority: 'high',
    moodSticker: 'coffee',
  },
  {
    id: 'ev-tue-3',
    title: 'Vinyasa Flow Yoga',
    category: 'personal',
    date: '2026-09-15',
    startTime: '17:30',
    endTime: '18:30',
    location: 'Campus Wellness Studio 2',
    notes: 'Decompress posture and shoulder tension.',
    priority: 'low',
    moodSticker: 'sparkles',
  },

  // WEDNESDAY · SEPTEMBER 16
  {
    id: 'ev-wed-1',
    title: 'Database Systems',
    category: 'university',
    date: '2026-09-16',
    startTime: '08:00',
    endTime: '09:30',
    location: 'Building 24 — Room 302',
    room: 'Room 302',
    instructor: 'Prof. David Vance',
    courseCode: 'CS302',
    notes: 'Transactions, ACID compliance, and two-phase locking.',
    priority: 'high',
    isRecurring: true,
    recurringDays: ['Monday', 'Wednesday'],
    moodSticker: 'book',
  },
  {
    id: 'ev-wed-2',
    title: 'Modern Literature Seminar',
    category: 'university',
    date: '2026-09-16',
    startTime: '11:30',
    endTime: '13:00',
    location: 'Hall 4 — Room 201',
    courseCode: 'ENG201',
    instructor: 'Prof. Julian Sterling',
    notes: 'Close-reading session on modern magical realism texts.',
    priority: 'medium',
    moodSticker: 'coffee',
  },
  {
    id: 'ev-wed-3',
    title: 'Java BST Problem Set Submission',
    category: 'assignments',
    date: '2026-09-16',
    startTime: '23:59',
    endTime: '23:59',
    location: 'Git Classroom Repository',
    courseCode: 'CS210',
    notes: 'Commit final test suite and pass all unit assertions.',
    priority: 'urgent',
    isTask: true,
    completed: false,
    isDeadline: true,
    moodSticker: 'star',
  },

  // FRIDAY · SEPTEMBER 18
  {
    id: 'ev-fri-1',
    title: 'Literature Essay First Draft Due',
    category: 'assignments',
    date: '2026-09-18',
    startTime: '17:00',
    endTime: '17:00',
    location: 'Turnitin Portal',
    courseCode: 'ENG201',
    notes: '1,500 words on thematic identity and memory narratives.',
    priority: 'high',
    isTask: true,
    completed: false,
    isDeadline: true,
    moodSticker: 'star',
  },
  {
    id: 'ev-fri-2',
    title: 'Dinner with Friends',
    category: 'social',
    date: '2026-09-18',
    startTime: '20:00',
    endTime: '22:30',
    location: 'Somewhere Café',
    notes: 'Celebrate completing week 3! Reserve table on patio.',
    priority: 'medium',
    moodSticker: 'heart',
  },

  // SUNDAY · SEPTEMBER 20 (From user prompt example!)
  {
    id: 'ev-sun2-1',
    title: 'Data Structures & Java Lecture',
    category: 'university',
    date: '2026-09-20',
    startTime: '10:00',
    endTime: '11:30',
    location: 'Building 12 — Room 105',
    courseCode: 'CS210',
    instructor: 'Prof. Helen Lin',
    priority: 'high',
    moodSticker: 'book',
  },
  {
    id: 'ev-sun2-2',
    title: 'Dentist Appointment',
    category: 'appointments',
    date: '2026-09-20',
    startTime: '17:00',
    endTime: '18:00',
    location: 'Campus Health Plaza — Suite 102',
    notes: 'Routine 6-month cleaning & polishing. Dr. Sarah Chen.',
    priority: 'high',
    moodSticker: 'sparkles',
  },
];
